home/urls.py
from django.urls import path
from . import views

# application namespace
ap_name = 'home' 
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('login', views.LoginInterfaceView.as_view(), name='login'),
    path('logout', views.LogoutInterfaceView.as_view(), name='logout'),
    path('signup', views.SignupView.as_view(), name='signup'),
]

notes/urls.py
from django.urls import path
from . import views

app_name = 'notes'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/edit', views.UpdateNoteView.as_view(), name='edit'),
    path('<int:pk>/delete', views.DeleteNoteView.as_view(), name='delete'),
    path('create', views.CreateNoteView.as_view(), name='create'),
]

smartnotes/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('', include('home.urls')),
    path('notes/', include('notes.urls')),
    path('admin/', admin.site.urls),
]

home/models.py
from django.db import models

# Create your models here.

notes/models.py
from django.db import models
from django.contrib.auth.models import User

class Notes(models.Model):
    title = models.CharField(max_length=200)
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    # A user may have 0, 1 or more notes. A note must belong to one and only one user.
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='notes')

    def __str__(self):
        return self.title

notes/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import Notes

class NotesForm(forms.ModelForm):
    class Meta:
        model = Notes
        fields = ('title', 'text')
        widgets = {
            'title': forms.TextInput(),
            'text': forms.Textarea(),
        }
        labels = {
            'text': 'add your note:'
        }

    def clean_title(self):
        title = self.cleaned_data['title']
        if len(title.strip()) <= 5:
            raise ValidationError('Title is too short')
        return title

home/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse, HttpResponseRedirect
# from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView
from django.views.generic.edit import CreateView
from django.contrib.auth import login
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from datetime import datetime

# Create your views here.
# def index(request):
#     context = { 'today': datetime.today()}
#     return render(request, 'home/index.html', context)

class IndexView(TemplateView):
    template_name = 'home/index.html'
    extra_context = {'today': datetime.today()}

class LoginInterfaceView(LoginView):
    template_name = 'home/login.html'

class LogoutInterfaceView(LogoutView):
    template_name = 'home/logout.html'

class SignupView(CreateView):
    form_class = UserCreationForm
    template_name = 'home/signup.html'
    success_url = '/notes'

    def get(self, request, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect('notes:index')
        return super().get(request, *args, **kwargs)

    def form_valid(self, form):
        """
        if the form is valid, authenticate the user and
        redirect to the supplied URL.
        """
        self.object = form.save()
        login(self.request, self.object)
        return HttpResponseRedirect(self.get_success_url())

notes/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.views.generic import ListView, DetailView, TemplateView, CreateView, UpdateView
from django.views.generic.edit import DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin

from .forms import NotesForm
from .models import Notes

# def index(request):
#     note_list = Notes.objects.all()
#     context = { 'notes': note_list}
#     return render(request, 'notes/index.html', context)

# IndexView is a subclass of generic.ListView,
# it is performing the same task as the index function() specified above.
# To handle Login in a Class View we must use a mixin - LoginRequiredMixin,
# it must be specified before the generic View in this case Template View
class IndexView(LoginRequiredMixin, ListView):
    # By default Django will look for a template called -> <app name>/<model name>_list.html
    # We are using the attribute template_name to override the template name Django should look for
    template_name = 'notes/index.html'
    context_object_name = 'notes'
    login_url = '/login'

    # Using type hint for code readability
    def get_queryset(self) -> QuerySet[Notes]:
        # get all the notes related to the current logged in user
        return self.request.user.notes.all()
    
# pk is the parameter url specified in urls.py
# def detail(request, pk):
#     try:
#         note = Notes.objects.get(pk=pk)
#     except Notes.DoesNotExist:
#         raise Http404('Note does not exist in the database')

#     context = { 'note': note }
#     return render(request, 'notes/detail.html', context)


# DetailView will handle a Notes.DoesNotExist,
# redirecting the user to the 404 Page Not Found and displaying an appropiate message
class DetailView(DetailView):
    model = Notes
    context_object_name = 'note'
    template_name = 'notes/detail.html'


# class NewView(TemplateView):
#     template_name = 'notes/new.html'

# def create(request):
#     if ((title := request.POST['title'] == "") and (text := request.POST['text'] == "")):
#         context = {
#             'error_msg': 'all fields are required'
#         }
#         return render(request, 'notes/form.html', context)
#     else:
#         Notes.objects.create(title=title, text=text)
#         return HttpResponseRedirect(reverse('notes:index'))
    
#Django generic CreateView class handles GET and POST requests made to the same url (notes/create)
class CreateNoteView(LoginRequiredMixin, CreateView):
    # When a POST request is made to notes/create a new Note is created in the database,
    # and the user is redirected to notes/ (notes:index)
    model = Notes
    # Using Django forms
    form_class = NotesForm
    # When a GET request is made to notes/create the user is displayed the notes/new.html template
    # to submit a new POST request to create a Note in the database
    # Used for GET requests to the url notes/create
    template_name = 'notes/form.html' 
    success_url = '/notes'
    login_url ='/login'

    def form_valid(self, form):
        """
        if the form is valid, add the current user to the note created, and
        redirect to the supplied URL.
        """
        # self.object is the object being updated, save(commit=False) create, but do not save the new note instance
        self.object = form.save(commit=False)
        # self.request.user refers to the current logged in user
        self.object.user = self.request.user
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


class UpdateNoteView(UpdateView):
    model = Notes
    form_class = NotesForm
    template_name = 'notes/form.html'
    success_url = '/notes'

class DeleteNoteView(DeleteView):
    model = Notes
    template_name = 'notes/delete_confirmation_form.html'
    success_url = '/notes'

home/templates/home/index.html
{% extends 'base.html' %}

{% block title %}
  <title>Home</title>
{% endblock title %}

{% block content %}
<main>
    <h1>Welcome to SmartNotes!</h1>
    <p>Date: {{ today }}</p>
</main>
{% endblock content %}

home/templates/home/login.html
{% extends 'base.html' %}

{% block title %}
<title>Login</title>
{% endblock  %}

{% block content %}
<main>
    <form method="post">
    {% csrf_token %}
        {{ form.as_p}}
        <input type="submit" value="Login">
    </form>
</main>
{% endblock  %}

home/templates/home/logout.html
{% extends 'base.html' %}

{% block title %}
<title>Logout</title>
{% endblock %}

{% block content %}
<h1>Thanks for visiting Notes app</h1>
{% endblock  %}

home/templates/home/signup.html
{% extends 'base.html' %}

{% block style %}
    <style>
    #id_usable_password {
        display:none
    }
    </style>
{% endblock  %}

{% block title %}
<title>SignUp</title>
{% endblock  %}

{% block content %}
<main>
    <form method="post">
    {% csrf_token %}
        {{ form.as_p}}
        <input type="submit" value="SignUp">
    </form>
</main>
{% endblock  %}

notes/templates/notes/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="keywords" content="Django Web Framework, Django Template Language, SmartNotes App">
    <meta name="author" content="Alexander Gutierrez">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
    {% comment %} {% load static %}
    <link rel="stylesheet" href="{% static 'polls/css/style.css' %}"> {% endcomment %}

    {% block style %}{% endblock %}
    
    {% block title %}{% endblock %}
</head>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>

notes/templates/notes/delete_confirmation_form.html
{% extends 'base.html' %}

{% block title %}
{% endblock %}

{% block content %}
<main> 
    <form method="post">
    {% csrf_token %}
        <div>
            <h3>Are you sure you want to delete `{{ notes.title }}`?</h3>
            <p>This action can't be reversed</p>
        </div>
        <input type="Submit" value="Delete">
    </form>
    <a href="{% url 'notes:index' %}">Cancel</a>
</main>
{% endblock%}

notes/templates/notes/detail.html
{% extends 'base.html' %}

{% block title %}
<title>Note Detail</title>
{% endblock title %}

{% block content %}
<main>
    <h1>{{ note.title }}</h1>
    <p>{{ note.text }}</p>
    <em>{{ note.created }}<em>
    <a href="{% url 'notes:index' %}">Notes</a>
    <a href="{% url 'notes:edit' note.id %}">Edit</a>
    <a href="{% url 'notes:delete' note.id %}">Delete</a>
</main>
{% endblock content %}

notes/templates/notes/form.html
{% extends 'base.html' %}

{% block title %}
<title>New Note</title>
{% endblock title %}

{% load static %}
{% block style %}
    <link rel="stylesheet" type="text/css" href="{% static 'notes/css/newStyle.css' %}">
{% endblock %}

{% block content %}
<main>
    {# the action attribute is not needed when using Django class forms because it's value is generated according to the action (Create, update) #}
    <form method="post">
    {# Cross-Site Request Forgery #}
    {# comment Django uses a csrf token to know the POST request comes from a legit user #}
    {% csrf_token %}
        {{ form.as_p }}
        <div>
            <input type="submit" value="Submit">
        </div>
    </form>
    <a href="{% url 'notes:index' %}">Cancel</a>
    {% if form.errors %}
    <div>
        {{ form.errors.title.as_text }}
        {{ form.errors.text.as_text }}
    </div>
    {% endif %}
</main>
{% endblock content %}

notes/templates/notes/index.html
{% extends 'base.html' %}

{% block title %}
<title>Notes</title>
{% endblock title %}

{% block content %}
<main>
    <h1>Notes</h1>
    {% if notes %}
        <ul>
            {% for note in notes %}
                <li><a href="{% url 'notes:detail' note.id %}">{{ note.title | title }}</a></li>
            {% endfor %}
        </ul>
        <div>
            <a href="{% url 'notes:create' %}">Add a note</a>
        </div>
    {% else %}
        <div>
            <h3>Start adding notes</h3>
            <a href="{% url 'notes:create' %}">Add a note</a>
        </div>
    {% endif %}
</main>
{% endblock content %}

notes/templates/notes/new.html
{% block title %}
<title>New Note</title>
{% endblock title %}

{% load static %}
{% block style %}
    <link rel="stylesheet" type="text/css" href="{% static 'notes/css/newStyle.css' %}">
{% endblock %}

{% block content %}
<main>
    <form action="{% url 'notes:create' %}" method="post">
    {# Cross-Site Request Forgery #}
    {# comment Django uses a csrf token to know the POST request comes from a legit user #}
    {% csrf_token %}
        {{ form.as_p }}
        <div>
            <input type="submit" value="Create">
        </div>
    </form>
    {% if form.errors %}
    <div>
        {{ form.errors.title.as_text }}
        {{ form.errors.text.as_text }}
    </div>
    {% endif %}
</main>
{% endblock content %}